# Generated by Django 3.2.19 on 2023-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0009_siteroutecomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteroutecomment',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
