# Generated by Django 3.2.19 on 2023-06-29 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0014_rename_own_route_ownroute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownroute',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='ownroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
