# Generated by Django 3.2.19 on 2023-06-29 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0015_auto_20230629_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
