# Generated by Django 3.2.19 on 2023-06-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event1',
        ),
        migrations.DeleteModel(
            name='Event2',
        ),
        migrations.DeleteModel(
            name='Event3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
