# Generated by Django 3.2.19 on 2023-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0002_auto_20230623_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own_route',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
