# Generated by Django 3.2.19 on 2023-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0003_alter_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='own_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter name', max_length=80)),
                ('start_point', models.CharField(default='enter name', max_length=80)),
                ('end_point', models.CharField(default='enter name', max_length=80)),
                ('difficulty_rating', models.CharField(default='enter name', max_length=80)),
                ('description', models.CharField(default='enter name', max_length=80)),
            ],
        ),
    ]
