# Generated by Django 3.2.19 on 2023-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0004_own_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='own_route',
            name='image',
            field=models.ImageField(default='enter image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='own_route',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='own_route',
            name='difficulty_rating',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='own_route',
            name='end_point',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='own_route',
            name='start_point',
            field=models.CharField(max_length=80),
        ),
    ]
