# Generated by Django 3.2.19 on 2023-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0004_auto_20230623_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecomment',
            name='email',
            field=models.EmailField(default='adfsad', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routecomment',
            name='name',
            field=models.CharField(default='adfasd', max_length=80),
            preserve_default=False,
        ),
    ]
