# Generated by Django 3.2.19 on 2023-06-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0005_auto_20230623_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routecomment',
            name='email',
        ),
    ]
