# Generated by Django 3.2.19 on 2023-06-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0007_siteroutecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(null=True, default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
