# Generated by Django 3.2.19 on 2023-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0009_event1_event2_event3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='enter name', max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('route', models.CharField(choices=[('milstatt', 'Milstatt'), ('bad_kleikircheim', 'Bad Kleikircheim'), ('villach', 'Villach'), ('wortersee', 'Wortersee')], max_length=20)),
            ],
        ),
    ]
