# Generated by Django 3.2.19 on 2023-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0010_siteroutecomment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteroutecomment',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
        ),
    ]
