# Generated by Django 3.2.19 on 2023-06-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_site', '0012_alter_siteroutecomment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteroutecomment',
            name='slug',
        ),
    ]
